<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise Chaining</title>
</head>
<body>
    
</body>


<script>
     // Promise Chaining

     function asyncFunc1(){
        return new Promise((resolve , reject) => {
            setTimeout(() => {
                console.log("data1");
                resolve("success")
            } , 4000)
        })
     }
     function asyncFunc2(){
        return new Promise((resolve , reject) => {
            setTimeout(() => {
                console.log("data2");
                resolve("success")
            } , 4000)
        })
     }


    //  console.log("fetching data1...");
    //  let p1 = asyncFunc1()
    //  p1.then((res) => {
    //      console.log("fetching data2...");
    //      let p2 = asyncFunc2()
    //      p2.then((res) =>{})
    //  });




     function getData(dataId, getNextData) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (dataId) {
                    console.log("data :", dataId);
                    resolve("Success");
                } else {
                    reject("Fail");
                }
                if (getNextData) {
                    getNextData();
                }
            }, 3000);
        });
    }
    
    // promise chaining 

    // getData(1)
    // .then((result) => {
    //     return getData(2)
    //     .then(res => {
    //         return getData(3)
    //         .then(res => {console.log(res);})
    //     })
    // })

    // getData(1)
    // .then((res) => {
    //     return getData(2)
    // })
    // .then(res => {
    //     return getData(3)
    // }).then(res => console.log(res))


    //promise.all()

    function load(url , success = true){
        return new Promise((resolve , reject) => {
            setTimeout(() => {
                if(success){
                    resolve(`Data from ${url}`)
                }else{
                    reject(`Error : Url not found`)
                }
            }, 2000);
        })
    }


    const url1 = 'https://api1.com';
    const url2 = 'https://api2.com';
    const url3 = 'https://api3.com';

    Promise.all([load(url1) , load(url2 , false) , load(url3)])
    .then((result) => {
        console.log(result);
    })
    .catch((err) => {
        console.log(err); // If any of the promises fail, this block will run
    });

</script>
</html>